[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
solc_version = "0.8.26"

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
  '@prb/math/=lib/prb-math/',
  '@BokkyPooBahsDateTimeLibrary/contracts=lib/BokkyPooBahsDateTimeLibrary/contracts',
]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", chain = 8543, url = "https://api.basescan.org/api" }

[invariant]
fail_on_revert = false
runs = 1215
depth = 23
