[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
  '@prb/math/=lib/prb-math/',
]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
