[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
  '@prb/math/=lib/prb-math/',
  '@BokkyPooBahsDateTimeLibrary/contracts=lib/BokkyPooBahsDateTimeLibrary/contracts',
]

[rpc_endpoints]
base = "${BASE_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
optimism = { key = "${OPTIMISMSCAN_API_KEY}" }
